# Generated by Django 2.2.24 on 2022-11-04 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('certificate', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.CharField(default='devhiuse', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientanswer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='classroom.Patient'),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='classroom.Patient'),
        ),
    ]
