# Generated by Django 2.2.24 on 2022-11-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_user_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.CharField(default='devhiuse', max_length=100),
        ),
    ]
